version: '3.3'

services:
  server:
    build: .
    ports:
      - '80:80'
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'pass420'
      MYSQL_ROOT_PASSWORD: 'pass420'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: